ContosoUDemo/Controllers/StudentEnrollmentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ContosoUDemo.DAL;
using ContosoUDemo.Models;
//mwilliams
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
//end mwilliams

namespace ContosoUDemo.Controllers
{
    /*mwilliams:  add role based authorization*/
    [Authorize(Roles = "student")]
    public class StudentEnrollmentController : Controller
    {
        private SchoolContext db = new SchoolContext();

        // GET: StudentEnrollment
        public ActionResult Index()
        {
            //get logged in user's id
            string userId = User.Identity.GetUserId();

            if (!string.IsNullOrEmpty(userId))
            {
                //locate this user within student entity
                var manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(ApplicationDbContext.Create()));
                var currentStudent = manager.FindByEmail(User.Identity.GetUserName());//username and email are the same

                Student student = db.Students
                    .Include(i => i.Enrollments)
                    .Where(i => i.Email == currentStudent.Email).Single();

                // Create and execute raw SQL query:  Get all courses that this student i. 
                string query = "SELECT CourseID, Title FROM Course WHERE CourseID NOT IN(SELECT DISTINCT CourseID FROM Enrollment WHERE StudentID = @p0)";
                IEnumerable<ViewModels.AssignedCourseData> data = db.Database.SqlQuery<ViewModels.AssignedCourseData>(query, student.ID);
                ViewBag.Courses = data.ToList();


                var studentEnrollments = db.Enrollments.Include(e => e.Course).Include(e => e.Student).Where(e => e.Student.Email == currentStudent.Email);
                return View(studentEnrollments.ToList());
            }
            else
            {
                //return HttpNotFound();
                return View("Error");

            }
        }
        

        // GET: StudentEnrollment/Enroll
        public ActionResult Enroll(int? courseId)
        {

            if (courseId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            string userId = User.Identity.GetUserId();
            if (!string.IsNullOrEmpty(userId))
            {
                var manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(ApplicationDbContext.Create()));
                var currentStudent = manager.FindByEmail(User.Identity.GetUserName());//username and email are the same

                Student student = db.Students
                    .Include(i => i.Enrollments)
                    .Where(i => i.Email == currentStudent.Email).Single();
                ViewBag.StudentID = student.ID;

                var studentEnrollments = new HashSet<int>(db.Enrollments.Include(e => e.Course).Include(e => e.Student).Where(e => e.Student.Email == currentStudent.Email).Select(e => e.CourseID));
                //fix for dealing with conversion int? to int
                int currentCourseID;
                if (courseId.HasValue)
                {
                    currentCourseID = (int)courseId;
                }
                else
                {
                    currentCourseID = 0;
                }
                //end of conversion fix

                if (studentEnrollments.Contains(currentCourseID))
                {
                    //return HttpNotFound();
                    //ViewBag.AlreadyEnrolledError = "You are already enrolled in this course";
                    ModelState.AddModelError("AlreadyEnrolled", "You are already enrolled in this course");
                }

            }

            Course course = db.Courses.Find(courseId);
            if (course == null)
            {
                return HttpNotFound();
            }


            return View(course);
        }


        // POST: StudentEnrollment/Enroll
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Enroll([Bind(Include = "CourseID,StudentID")] Enrollment enrollment)
        {
            if (ModelState.IsValid)
            {
                db.Enrollments.Add(enrollment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ContosoUDemo/Views/StudentEnrollment/Enroll.cshtml
@model ContosoUDemo.Models.Course
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Enrollment</h4>
        <hr />
        <p class="text-danger">
            @*@ViewBag.AlreadyEnrolledError*@
            @Html.ValidationMessage("AlreadyEnrolled")

        </p>
        @Html.HiddenFor(model => model.CourseID)
        <input type="hidden" name="StudentID" id="StudentID" value="@ViewBag.StudentID" />

        <div class="form-group">
            <label class="col-md-2">Selected Course:</label>
            <div class="col-md-10">
                @Html.DisplayFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        @*@if (ViewBag.AlreadyEnrolledError != "You are already enrolled in this course")*@
        @if (ViewData.ModelState.IsValid)
        {
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Enroll" class="btn btn-default" />
                </div>
            </div>
        }
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ContosoUDemo/Views/StudentEnrollment/Index.cshtml
@model IEnumerable<ContosoUDemo.Models.Enrollment>

@{
    ViewBag.Title = "Index";
}

<h2>Enrolled Courses</h2>

<table class="table">
    <tr>
        <th>
            Course @Html.DisplayNameFor(model => model.Course.CourseID)
        </th>
        <th>
            Course @Html.DisplayNameFor(model => model.Course.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Grade)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Course.CourseID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Course.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Grade)
            </td>
        </tr>
    }
</table>

<h2>Available Courses</h2>

<table class="table">
    <tr>
        <th>
            Course Number
        </th>
        <th>
            Title
        </th>
        <th></th>
    </tr>
    @{
        List<ContosoUDemo.ViewModels.AssignedCourseData> courses = ViewBag.Courses;

        foreach (var course in courses)
        {

            <tr>
                <td>
                    @Html.DisplayFor(modelItem => course.CourseID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => course.Title)
                </td>
                <td>
                    <a href="@Url.Action("Enroll", "StudentEnrollment",new { courseId = course.CourseID })" title="Enroll">Enroll</a> <span class="glyphicon glyphicon-plus-sign"></span>
                </td>
            </tr>
        }
    }
</table>