ContosoUDemo/Models/Student.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ContosoUDemo.Models
{
    public class Student : Person
    {
        //mwilliams:  Data Annotations
        /*
            DataType.Date:  we only want to keep track of the date, not the date and time.
                            Does not specify the format of the date that is displayed. 
                            By default, the data field is displayed according to the default formats based on 
                            the server's CultureInfo

            DisplayFormat:  Attribute is used to explicitly specify the date format, for example:  yyyy-MM-dd
                            The browser can enable HTML5 features (for example to show a calendar control, the locale-appropriate currency
                            symbol, email links, some client-side input validation, etc.).
            Display(Name=""): Gets or sets a value that is used for display in the UI overriding default EnrollmentDate.
        */
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Enrollment Date")]
        public DateTime EnrollmentDate { get; set; }
        public virtual ICollection<Enrollment> Enrollments { get; set; }//1 student : many enrollments
        /*
        The Enrollments property is a navigation property. Navigation properties hold other entities that are related to this entity. 
        In this case, the Enrollments property of a Student entity will hold all of the Enrollment entities that are related to that Student entity. 
        In other words, if a given Student row in the database has two related Enrollment rows (rows that contain that student's primary key value 
        in their StudentID foreign key column), that Student entity's Enrollments navigation property will contain those two Enrollment entities.

        Navigation properties are typically defined as virtual so that they can take advantage of certain Entity Framework functionality such as lazy loading. 
        */


    }
}

ContosoUDemo/Controllers/EnrollmentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ContosoUDemo.DAL;
using ContosoUDemo.Models;

namespace ContosoUDemo.Controllers
{
    /*mwilliams:  add role based authorization*/
    [Authorize(Roles = "admin")]

    public class EnrollmentController : Controller
    {
        private SchoolContext db = new SchoolContext();

        // GET: Enrollment
        public ActionResult Index()
        {
            var enrollments = db.Enrollments.Include(e => e.Course).Include(e => e.Student);
            return View(enrollments.ToList());
        }

        // GET: Enrollment/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Enrollment enrollment = db.Enrollments.Find(id);
            if (enrollment == null)
            {
                return HttpNotFound();
            }
            return View(enrollment);
        }

        // GET: Enrollment/Create
        public ActionResult Create()
        {
            ViewBag.CourseID = new SelectList(db.Courses, "CourseID", "Title");
            //mwilliams:  
            //ViewBag.StudentID = new SelectList(db.People, "ID", "LastName");
            //ViewBag.StudentID = new SelectList(db.Students, "ID", "LastName");
            ViewBag.StudentID = new SelectList(db.Students, "ID", "FullName");
            return View();
        }

        // POST: Enrollment/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EnrollmentID,CourseID,StudentID,Grade")] Enrollment enrollment)
        {
            if (ModelState.IsValid)
            {
                db.Enrollments.Add(enrollment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CourseID = new SelectList(db.Courses, "CourseID", "Title", enrollment.CourseID);
            ViewBag.StudentID = new SelectList(db.People, "ID", "LastName", enrollment.StudentID);
            return View(enrollment);
        }

        // GET: Enrollment/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Enrollment enrollment = db.Enrollments.Find(id);
            if (enrollment == null)
            {
                return HttpNotFound();
            }
            ViewBag.CourseID = new SelectList(db.Courses, "CourseID", "Title", enrollment.CourseID);
            ViewBag.StudentID = new SelectList(db.People, "ID", "LastName", enrollment.StudentID);
            return View(enrollment);
        }

        // POST: Enrollment/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EnrollmentID,CourseID,StudentID,Grade")] Enrollment enrollment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(enrollment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CourseID = new SelectList(db.Courses, "CourseID", "Title", enrollment.CourseID);
            ViewBag.StudentID = new SelectList(db.People, "ID", "LastName", enrollment.StudentID);
            return View(enrollment);
        }

        // GET: Enrollment/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Enrollment enrollment = db.Enrollments.Find(id);
            if (enrollment == null)
            {
                return HttpNotFound();
            }
            return View(enrollment);
        }

        // POST: Enrollment/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Enrollment enrollment = db.Enrollments.Find(id);
            db.Enrollments.Remove(enrollment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ContosoUDemo/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ContosoUDemo.DAL;
using ContosoUDemo.Models;
using PagedList;
using ContosoUDemo.ViewModels;

namespace ContosoUDemo.Controllers
{
    /*mwilliams:  add role based authorization*/
    [Authorize(Roles = "admin")]

    public class StudentController : Controller
    {
        private SchoolContext db = new SchoolContext();

        // GET: Student
        //public ActionResult Index()
        //{
        //    return View(db.Students.ToList());
        //}
        /*mwilliams:  Added Sorting, filtering and paging */
        public ActionResult Index(string sortOrder, string searchString, int? page, string currentFilter)//Sorting, filtering and paging
        {

            //mwilliams: for paging
            ViewBag.CurrentSort = sortOrder;
            //mwilliams: for sorting
            ViewBag.LNameSortParm = String.IsNullOrEmpty(sortOrder) ? "lname_desc" : "";
            ViewBag.FNameSortParm = sortOrder == "fname" ? "fname_desc" : "fname";
            ViewBag.EmailSortParm = sortOrder == "email" ? "email_desc" : "email";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";

            //mwilliams: for filtering
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;


            //get students
            var students = from s in db.Students
                           select s;

            //mwilliams: for filtering
            if (!string.IsNullOrEmpty(searchString))
            {
                students = students.Where(s => s.LastName.Contains(searchString) || s.FirstMidName.Contains(searchString));
            }                

            //mwilliams:  apply sort
            switch (sortOrder)
            {
                case "lname_desc":
                    students = students.OrderByDescending(s => s.LastName);
                    break;
                case "fname":
                    students = students.OrderBy(s => s.FirstMidName);
                    break;
                case "fname_desc":
                    students = students.OrderByDescending(s => s.FirstMidName);
                    break;
                case "email":
                    students = students.OrderBy(s => s.Email);
                    break;
                case "email_desc":
                    students = students.OrderByDescending(s => s.Email);
                    break;
                case "Date":
                    students = students.OrderBy(s => s.EnrollmentDate);
                    break;
                case "date_desc":
                    students = students.OrderByDescending(s => s.EnrollmentDate);
                    break;
                default:  // Name ascending 
                    students = students.OrderBy(s => s.LastName);
                    break;
            }
            //mwilliams: for paging
            //return View(students.ToList());
            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(students.ToPagedList(pageNumber, pageSize));
        }

        // GET: Student/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // GET: Student/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Student/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.

        /* mwilliams
          The ValidateAntiForgeryToken attribute helps prevent cross-site request forgery attacks. 
          It requires a corresponding Html.AntiForgeryToken() statement in the view
        */
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "LastName,FirstMidName,Email,EnrollmentDate")] Student student)
        {
            /*mwilliams:  exception handling (try...catch)
              and remove ID from the Bind attribute for the scaffolded method  because ID is the primary key value which 
              SQL Server will set automatically when the row is inserted. Input from the user does not set the ID value            
            */

            try
            {
                if (ModelState.IsValid)
                {
                    db.People.Add(student);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException /*dex*/)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }
            /*  mwilliams
                DataException exceptions are sometimes caused by something external to the application rather than a programming error, 
                so the user is advised to try again. 
                
                Although not implemented in this sample, a production quality application would log the exception. 
            */


            return View(student);
        }

        // GET: Student/Edit/5
        /* mwilliams */
        //public ActionResult Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Student student = db.Students.Find(id);
        //    if (student == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(student);
        //}

        public ActionResult Edit(int? id, int? page)//mwilliams adding paging sticky
        {
            ViewBag.CurrentPage = page;

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.Students
                .Include(i => i.Enrollments)
                .Where(i => i.ID == id)
                .Single();
            PopulateAssignedCourseData(student);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        private void PopulateAssignedCourseData(Student student)
        {
            var allCourses = db.Courses;
            var studentCourses = new HashSet<int>(student.Enrollments.Select(c => c.CourseID));
            var viewModel = new List<AssignedCourseData>();
            foreach (var course in allCourses)
            {
                viewModel.Add(new AssignedCourseData
                {
                    CourseID = course.CourseID,
                    Title = course.Title,
                    Assigned = studentCourses.Contains(course.CourseID)
                });
            }
            ViewBag.Courses = viewModel;
        }
        /* end mwilliams */

        // POST: Student/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "ID,LastName,FirstMidName,Email,EnrollmentDate")] Student student)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(student).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    return View(student);
        //}

        /*mwillams:  protect from overposting 
          The scaffolder generated a Bind attribute and added the entity created by the model binder to the entity set with a Modified flag. 
          That code is no longer recommended because the Bind attribute clears out any pre-existing data in fields not listed in the Include parameter.
          
            As a best practice to prevent overposting, the fields that you want to be updateable by the Edit page are whitelisted in the 
            TryUpdateModel parameters. Currently there are no extra fields that you're protecting, but listing the fields that you want the 
            model binder to bind ensures that if you add fields to the data model in the future, they're automatically protected until you explicitly add them here. 
        */
        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public ActionResult EditPost(int? id, string[] selectedCourses)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
           var studentToUpdate = db.Students.Find(id);
            //var studentToUpdate = db.Students
            //   .Include(s => s.Enrollments)
            //   .Where(i => i.ID == id)
            //   .Single();

            if (TryUpdateModel(studentToUpdate, "",
               new string[] { "LastName", "FirstMidName", "Email","EnrollmentDate" }))
            {
                try
                {
                    //mwilliams:  enrollment
                    UpdateStudentCourses(selectedCourses, studentToUpdate);
                    db.SaveChanges();

                    return RedirectToAction("Index");
                }

ContosoUDemo/Views/Student/Create.cshtml
@model ContosoUDemo.Models.Student

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Student</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstMidName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstMidName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstMidName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EnrollmentDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EnrollmentDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EnrollmentDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ContosoUDemo/Views/Student/Delete.cshtml
@model ContosoUDemo.Models.Student

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>
@* mwilliams add error message for delete *@
<p class="error">@ViewBag.ErrorMessage</p>
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Student</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstMidName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstMidName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EnrollmentDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EnrollmentDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ContosoUDemo/Views/Student/Details.cshtml
@model ContosoUDemo.Models.Student

@{
    ViewBag.Title = "Details";
}

<ol class="breadcrumb">
    <li>@Html.ActionLink("Home", "Index", "Home")</li>
    <li>@Html.ActionLink("Students", "Index", "Student")</li>
    <li class="active">@Html.DisplayFor(model => model.FirstMidName) @Html.DisplayFor(model => model.LastName)</li>
</ol>
<h2>Details</h2>

<div>
    <h4>Student</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstMidName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstMidName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>@* mwilliams:  remove mailto when using [DataType(DataType.EmailAddress)] in model
              @Html.DisplayFor(model => model.Email)*@
            @Html.DisplayTextFor(model=> model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EnrollmentDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EnrollmentDate)
        </dd>
        @* mwilliams:  added student enrollment *@
        <dt>
            @Html.DisplayNameFor(model => model.Enrollments)
        </dt>
        <dd>
            <table class="table">
                <tr>
                    <th>Course Title</th>
                    <th>Grade</th>
                    <th>&nbsp;</th>
                </tr>
                @foreach (var item in Model.Enrollments)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Course.Title)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Grade)
                        </td>
                        @* mwilliams added links *@
                        <td>
                            @if (String.IsNullOrEmpty(item.Grade.ToString()))
                            {
                                <a href="@Url.Action("Edit","Enrollment",new { id = item.EnrollmentID })" title="Edit Grade">Add Grade</a> <span class="glyphicon glyphicon-pencil"></span>
                            }
                            else
                            {
                                <a href="@Url.Action("Edit","Enrollment",new { id = item.EnrollmentID })" title="Edit Grade">Edit Grade</a> <span class="glyphicon glyphicon-edit"></span>
                            }

                        </td>
                    </tr>
                }
            </table>
        </dd>
        @* end mwilliams:  student enrollment *@
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ContosoUDemo/Views/Student/Edit.cshtml
@model ContosoUDemo.Models.Student

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Student</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstMidName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstMidName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstMidName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EnrollmentDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EnrollmentDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EnrollmentDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2" for="EnrollmentDate">Courses</label>
            <div class="col-md-10">
                <table class="table table-condensed">
                    @{
                            int cnt = 0;
                            List<ContosoUDemo.ViewModels.AssignedCourseData> courses = ViewBag.Courses;

                            foreach (var course in courses)
                            {
                                if (cnt++ % 3 == 0)
                                {
                                    @:<tr>
                                }
                                @:<td>
                                    <input type="checkbox"
                                           name="selectedCourses"
                                           value="@course.CourseID"
                                           @(Html.Raw(course.Assigned ? "checked=\"checked\"" : "")) />
                                        @course.CourseID @:  @course.Title
                                        @:</td>
                            }
                            @:</tr>
                        }
                    </table>
                </div>
            </div>


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
}

<div>
    @*mwilliams:  added paging sticky
            @Html.Raw(ViewBag.CurrentPage)
        @Html.ActionLink("Back to List", "Index")*@
    @Html.ActionLink("Back to List", "Index", new { page = ViewBag.CurrentPage })


</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ContosoUDemo/Views/Student/Index.cshtml
@* mwilliams:  added paging *@
@*@model IEnumerable<ContosoUDemo.Models.Student>*@
@model PagedList.IPagedList<ContosoUDemo.Models.Student>
@using PagedList.Mvc;
@*<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />*@

@{
    ViewBag.Title = "Students";
}

<h2>Students</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@* mwilliams: add search capability *@
@using (Html.BeginForm("Index","Student",FormMethod.Get))
{
    <p>
        Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" class="btn btn-sm btn-default"/>
    </p>
}
<table class="table">
    @* mwilliams:  added sorting *@
    <tr>
        <th>
            @*@Html.DisplayNameFor(model => model.LastName)
              @Html.ActionLink("Last Name", "Index", new { sortOrder = ViewBag.LNameSortParm })*@
            @Html.ActionLink("Last Name", "Index", new { sortOrder = ViewBag.LNameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.FirstMidName)
              @Html.ActionLink("First Name", "Index", new { sortOrder = ViewBag.FNameSortParm })*@
            @Html.ActionLink("First Name", "Index", new { sortOrder = ViewBag.FNameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Email)
              @Html.ActionLink("Email", "Index", new { sortOrder = ViewBag.EmailSortParm })*@
            @Html.ActionLink("Email", "Index", new { sortOrder = ViewBag.EmailSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.EnrollmentDate)
              @Html.ActionLink("Enrollment Date", "Index", new { sortOrder = ViewBag.DateSortParm })*@
            @Html.ActionLink("Enrollment Date", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstMidName)
            </td>
            <td>
                @*mwilliams: remove mailto when using [DataType(DataType.EmailAddress)] in model
                  @Html.DisplayFor(modelItem => item.Email)*@
                @Html.DisplayTextFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EnrollmentDate)
            </td>
            @* mwilliams:  add enrollments *@
            <td>
                @{
                    foreach (var enroll in item.Enrollments)
                    {
                        @* mwilliams: Using @: to explicitly indicate the start of content
                    in this case it will add a space
                    http://weblogs.asp.net/scottgu/asp-net-mvc-3-razor-s-and-lt-text-gt-syntax
                        *@
                        @enroll.CourseID @: @enroll.Course.Title
                        <a href="@Url.Action("Details","Course",new { id = enroll.CourseID })"> <span class="glyphicon glyphicon-eye-open"></span></a>
                        <br />
                    }
                }
            </td>
            @* mwilliams:  end enrollments *@
            <td>
                @*@Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })*@
                @* mwilliams added paging sticky *@
                @Html.ActionLink("Edit", "Edit", new { id = item.ID, page = Model.PageNumber }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID, page = Model.PageNumber }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID, page = Model.PageNumber })
            </td>
        </tr>
    }

</table>
@* mwilliams:  added paging links *@
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))